/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e6e8ea",
        "primary": "#004ac6",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "on-background": "#191c1e",
        "tertiary-fixed-dim": "#b9c7e0",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed-variant": "#3f465c",
        "secondary": "#565e74",
        "outline-variant": "#c3c6d7",
        "on-surface-variant": "#434655",
        "error-container": "#ffdad6",
        "tertiary-container": "#606e84",
        "on-tertiary-fixed-variant": "#3a485c",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#eeefff",
        "primary-container": "#2563eb",
        "surface-bright": "#f7f9fb",
        "background": "#f7f9fb",
        "secondary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#bec6e0",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed": "#0d1c2f",
        "tertiary": "#48566b",
        "surface-variant": "#e0e3e5",
        "error": "#ba1a1a",
        "secondary-container": "#dae2fd",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-tint": "#0053db",
        "inverse-on-surface": "#eff1f3",
        "on-error-container": "#93000a",
        "surface-container": "#eceef0",
        "inverse-surface": "#2d3133",
        "on-primary": "#ffffff",
        "surface": "#f7f9fb",
        "on-primary-fixed-variant": "#003ea8",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-container": "#5c647a",
        "on-surface": "#191c1e",
        "outline": "#737686",
        "on-primary-fixed": "#00174b",
        "inverse-primary": "#b4c5ff",
        "on-error": "#ffffff",
        "on-tertiary-container": "#eaf0ff",
        "tertiary-fixed": "#d5e3fd"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "panel-width": "400px",
        "sidebar-width": "280px",
        "container-max": "1280px",
        "gutter": "24px",
        "unit": "8px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
