import os
import asyncio
from typing import Dict, Any
from langchain_tavily import TavilySearch
from ...LearnerState import LearnerState, SwarmWorkerResult

async def practical_worker_node(state: LearnerState) -> Dict[str, Any]:
    """
    Practical Worker: Uses Tavily API to fetch general web resources and tutorials.
    """
    queries = state.get("swarm_queries", [])
    
    # Extract the web query generated by the Decomposer
    web_query_obj = next((q for q in queries if q["engine"] == "web"), None)
    if not web_query_obj:
        return {"swarm_raw_results": []}
        
    query = web_query_obj["query"]
    results = []
    
    try:
        # Initialize Tavily (automatically uses TAVILY_API_KEY from env)
        # max_results=2 to keep token usage lean for the Synthesizer
        tavily = TavilySearch(max_results=2)
        
        # Async execution to protect the event loop
        search_docs = await asyncio.to_thread(tavily.invoke, {"query": query})
        
        # Tavily returns a list of dicts: {"url": "...", "content": "..."}
        if isinstance(search_docs, list):
            for doc in search_docs:
                results.append(SwarmWorkerResult(
                    source_type="web",
                    raw_text=doc.get("content", ""), # Tavily returns clean, parsed text
                    source_url=doc.get("url", ""),
                    title=doc.get("title", "Web Resource"),
                    metadata={"source": "tavily"}
                ))
            
    except Exception as e:
        # Graceful degradation - if we hit the limit, the graph doesn't crash
        print(f"PracticalWorker failed: {e}") 
        pass 
        
    # Return as list so operator.add appends it to state
    return {"swarm_raw_results": results}
