from typing import Annotated, Any, Literal
from typing_extensions import TypedDict
import operator

class SwarmWorkerResult(TypedDict):
    source_type: str   # 'academic' | 'web' | 'video'
    raw_text: str
    source_url: str
    title: str
    metadata: dict

class SwarmQuery(TypedDict):
    engine: str        # 'academic' | 'web' | 'video'
    query: str

class LearnerState(TypedDict):
    """
    The central state object passed between all LangGraph nodes.
    Matches the full architecture plan schema.
    """
    # ── Identity ─────────────────────────────────────────────────────────────
    user_id: str
    session_id: str

    # ── Profile ──────────────────────────────────────────────────────────────
    user_profile: dict          # goal, background, learning_style, time_budget
    skill_map: dict             # topic → {level, confidence, last_assessed}

    # ── Curriculum ───────────────────────────────────────────────────────────
    master_curriculum: list     # list of LearningUnit dicts
    current_unit_index: int
    current_topic: str
    current_topic_id: str
    current_subtopic: str

    # ── Dialogue ─────────────────────────────────────────────────────────────
    # Uses `operator.add` reducer so nodes can safely append without overwriting
    conversation_history: Annotated[list[dict], operator.add]
    last_user_message: str

    # ── Assessment ───────────────────────────────────────────────────────────
    current_question: dict | None       # The active question being shown to the user
    user_answer: str                    # The user's last submitted answer
    evaluation: dict                    # {score, feedback, misconceptions}
    answered_questions: list            # Full history of Q+A this session
    current_batch_scores: list[float]   # Scores in the current 5-question batch
    consecutive_streak: int             # Consecutive correct-answer streak

    # ── Routing ──────────────────────────────────────────────────────────────
    next_route: str                     # Internal routing flag read by conditional edges
    remediation_needed: bool
    session_complete: bool

    # ── Circuit Breakers ─────────────────────────────────────────────────────
    loop_counters: dict[str, int]       # node_name → consecutive visit count
    error_context: dict | None          # {node, reason, last_input} — replaces plain error string

    # ── Legacy error field (kept for backward compat during transition) ───────
    error: str

    # ── Swarm Sub-Graph State ────────────────────────────────────────────────
    # swarm_queries: generated by QueryGenerator, consumed by 3 parallel workers
    swarm_queries: list[SwarmQuery]
    # `add` reducer: all three parallel workers append results concurrently
    swarm_raw_results: Annotated[list[SwarmWorkerResult], operator.add]
    # Final synthesized lesson, written by ContentSynthesizer
    content_module: str

    # ── Meta ─────────────────────────────────────────────────────────────────
    total_sessions: int
    flags: dict[str, Any]              # Feature flags, extensibility hook
